version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:6.0.13
    ports:
      - 6379:6379
